import Head from "next/head";
import styles from "../styles/Home.module.css";
import LogoGithub from "../components/Logos/LogoGithub";
import LogoDivtter from "../components/Logos/LogoDivtter";
import { loginWithGithub } from "../firebase/client";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Loading from "../components/Loading/Loading";
import useUser, { USER_STATES } from "../hooks/useUser";


export default function Home() {
    const user = useUser();
    const router = useRouter();
    const loginForms = [
        {
            name: "Github",
            color: "black",
            icon: <LogoGithub width={30} height={30} fill="white" />,
            function: loginWithGithub
        }
    ];
    
    useEffect(() => {
        user && router.replace("/home");
    }, [router, user]);
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Divter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/Logo.ico" />
            </Head>
            
            <main className={styles.main}>
                <LogoDivtter width={100} height={100} />
                <h1 className="title">Bienvenido a Divtter</h1>
                {user === USER_STATES.NOT_KNOWN && <Loading />}
                
                {user === USER_STATES.NOT_LOGGED && (
                    <>
                        {loginForms.map((form) => (
                            <button
                                key={form.name}
                                className={`btn ${form.color}`}
                                onClick={() => form.function()}
                            >
                                {form.icon}
                                Iniciar con {form.name}
                            </button>
                        ))}
                    </>
                )}
            </main>
            
            <style jsx>{`
              .title {
                color: #00a1e3;
              }

              .btn {
                width: 200px;
                height: 40px;
                border: none;
                border-radius: 20px;
                display: flex;
                place-items: center;
                text-align: center;
                cursor: pointer;
                margin-bottom: 5px;
              }

              .black {
                background-color: black;
                color: white;
              }

              .blue {
                background-color: #0072ea;
                color: white;
              }

              .btn:hover {
                opacity: 0.8;
              }

              .btn > :global(svg) {
                margin-right: 30px;
              }
            `}</style>
        </div>
    );
}
