import React from "react";
import Navbar from "../../components/NavBar/Navbar";
import Main from "../../components/Main/Main";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

function Home(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/Logo.ico" />
            </Head>
            <main>
                <Navbar />
                <Main />
            </main>
            
            <style jsx>{`
              main {
                display: flex;
              }
            `}</style>
        </div>
    );
}

export default Home;
